### ISSUE TITLE
LOLLLLL

### ISSUE THREAD

**Issue by muratvastark** [benerenla/basic_api#1]
Bro default files za xd xrd cry more trash project.

**Comment by benerenla** [comment]
mix phx.new deneme yaz kur kanka basit eline vurmuyorlar za xd

**Comment by muratvastark** [comment]
moruq sen öncelikle adam değilsin. ikinci olarak yaptığın proje çalıntı adam ol.

**Comment by sl34x** [comment]
YES! trash project

**Comment by Thealoq** [comment]
- - - - _[FazlaÇöp]()_

**Comment by muratvastark** [comment]
ben bir patatesim.

**Comment by Thealoq** [comment]
patatesss
